### ISSUE TITLE
HELP!  How to generate new key pair that works with sign-and-verify

### ISSUE THREAD

**Issue by jchartrand** [digitalcredentials/docs#11]
```
const {Ed25519VerificationKey2020} = require('@digitalbazaar/ed25519-verification-key-2020');

const test = async function() {
    const edKeyPair = await Ed25519VerificationKey2020.generate({controller: 'did:web:credentials.mcmaster.ca'})
    const keys = await edKeyPair.export({publicKey: true, privateKey: true});
    console.log(JSON.stringify(keys, null, 2))
}
test()
```

Produces:

```
{
  "id": "did:web:credentials.mcmaster.ca#z6MknS1QnArUMWypPxnWbeU2tcLuHzpBM8CzN1wSFwSAgFPy",
  "type": "Ed25519VerificationKey2020",
  "controller": "did:web:credentials.mcmaster.ca",
  "publicKeyMultibase": "z6MknS1QnArUMWypPxnWbeU2tcLuHzpBM8CzN1wSFwSAgFPy",
  "privateKeyMultibase": "zrv1DP1qkAyer4UvwCsAc1RxDH6VteU22r3v7VyLjkxTjYbamdikEKZ23wAtWe8wVL8iCgsxE1TskNWSXr6zQejCdmu"
}
```

You can see that the jwk fingerprint on the id is the same as the public key, which seems strange?

And this gives me this error when trying to use it to issue with the sign-and-verify libraries:

TypeError: `privateKeyBytes` must be a 64 byte Buffer.
    at privateKeyDerEncode (/Users/jc/gitlab github/mcmaster/dcc-cred-api/node_modules/@digitalcredentials/ed25519-verification-key-2020/dist/ed25519.js:118:11)

When I step through the code I can see that what gets passed into that method is a 66 byte Buffer, hence the error.

Any suggestions much appreciated.

**Comment by dmitrizagidulin** [comment]
Thanks! Will investigate.

**Comment by dmitrizagidulin** [comment]
@jchartrand - Ok, we tracked down the issue, and released major versions of the dependencies causing it.

If you update your deps to https://github.com/digitalcredentials/ed25519-verification-key-2020  v3.1.1 and reinstall, that error should go away. (Let me know if you run into anything else!)

**Comment by jchartrand** [comment]
Thanks @dmitrizagidulin !  What was the issue?  Or, could you direct me to where in the code I’d best try to understand the fundamental fix?

**Comment by dmitrizagidulin** [comment]
@jchartrand - so, this one was a breaking fix (having to do with matching the Ed25519 key spec) that happened upstream over at https://github.com/digitalbazaar/ed25519-verification-key-2020/blob/main/CHANGELOG.md#300---2021-06-19 

The basic upshot was that the key serialization gained an extra byte. So, the unserializing it to buffer resulted in the wrong length.

**Comment by jchartrand** [comment]
@dmitrizagidulin Okay, thanks!  I'd actually tried over the weekend with the latest digitalbazaar libraries for @digitalbazaar/vc, @digitalbazaar/ed25519-verification-key-2020 and @digitalbazaar/ed25519-signature-2020  (i.e., not the digital credential forks), and thought I had the same error with those too.  In any case, I will give your fix a try tomorrow.  Thanks very much again!

**Comment by dmitrizagidulin** [comment]
@jchartrand ah, right, so, `sign-and-verify-core` is using a slightly older version of the libraries, so the keys generated with new ones don't work. I'm about to make a PR to sign-and-verify-core to fix this.

**Comment by jchartrand** [comment]
@dmitrizagidulin I actually bypassed sign-and-verify-core completely and just signed directly with @digitalbazaar/vc (or at least tried to - I thought it gave me the same error, but I will check tomorrow.)  I think I get the error only when I run this in express, and not when I run it in node in a shell.

**Comment by jchartrand** [comment]
@dmitrizagidulin All appears to be working once again - thanks!
