### ISSUE TITLE
Update JFF Integration Guide to Include Issuer Registry Info

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/docs#20]
Please update [jff.md](https://github.com/digitalcredentials/docs/blob/main/integration/jff.md) to include information:

- Instructions for JFF participants issuing to the LCW about how to add themselves to the community registry via a github pull

(This is the most timely info needed)

Can also add:  

-  Background (why) about issuer registries and the ones we have
-  how the wallet and verifier use them

Suggest getting the first bullet published first if the next two may take a little longer to explain and need edits.

**Comment by jchartrand** [comment]
@kayaelle @dmitrizagidulin 

The four new registries (including the community) don't yet seem to have actual registry files yet:

https://github.com/digitalcredentials/community-registry
https://github.com/digitalcredentials/sandbox-registry
https://github.com/digitalcredentials/dcc-registry
https://github.com/digitalcredentials/dcc-pilot-registry

Should I commit one, at least to the community registry, so that it is easier for JFF partners to submit a PR for their DID. I'd follow the example of what's now in the 'old' registry:

https://github.com/digitalcredentials/issuer-registry/blob/main/registry.json

So, something like:

```
{
  "meta": {
    "created": "2020-12-02T02:32:16+0000",
    "updated": "2022-05-25T12:40:00+0000"
  },
  "registry": {
    "did:key:z6Mktpn6cXks1PBKLMgZH2VaahvCtBMF6K8eCa7HzrnuYLZv": {
      "name": "Example University 1 (DCC test-only issuer)",
      "location": "Cambridge, MA, USA",
      "url": "https://openlearning.mit.edu"
    },
    "did:key:z6MkqEwzA36k2PWsWpeQXjFMzT1PpZuVjZ9W9jd2ZGRb6JKr": {
      "name": "DCC Sandbox Issuer",
      "location": "Cambridge, MA, USA",
      "url": "https://verify.dcconsortium.org"
    },
    "did:key:z6MkhVTX9BF3NGYX6cc7jWpbNnR7cAjH8LUffabZP8Qu4ysC": {
      "name": "DCC Playground",
      "location": "Cambridge, MA, USA",
      "url": "https://digitalcredentials.github.io/playground"
    }
}

And should I include an existing DID in the community registry (maybe even the three DID I've listed above?), if only to serve as an example for whoever is first to submit a PR for their issuing DID?

**Comment by kayaelle** [comment]
@jchartrand - great question. I think an example is a good idea but suspect that they should be just examples and not real DIDs that are already in the main issuer registry. 

Follow-up question for @dmitrizagidulin: what happens if there are duplicate entries in multiple registries. Does the verifier quit after it finds one? What properties does it search for?

**Comment by jchartrand** [comment]
@kayaelle @dmitrizagidulin 

How about this as a starting registry (I made up the keys):

```
{
  "meta": {
    "created": "2020-12-02T02:32:16+0000",
    "updated": "2022-05-25T12:40:00+0000"
  },
  "registry": {
    "did:key:z6MkpLDL3RoAoMRTwTgo3rs39ZwssfaPKtGdZw7AGRN7CK4W": {
      "name": "My University",
      "location": "Cambridge, MA, USA",
      "url": "https://digitalcredentials.mit.edu"
    },
    "did:key:z6MkwcvAGvRUZk5TjdAZrBwQdaSYwDTbpEGjCrqR5zWU3Yf3": {
      "name": "My College",
      "location": "Prato, Italy",
      "url": "https://some.domain.org"
    },
    "did:web:credentials.myschool.ca": {
      "name": "My School",
      "location": "Ancaster, ON, Canada",
      "url": "https://some.domain.ca"
    }
}
```

**Comment by jchartrand** [comment]
Oh, and I guess the instructions should ask that anyone submitting a PR should also change the 'updated' date?

**Comment by jchartrand** [comment]
@kayaelle @dmitrizagidulin 

And maybe the instructions (and rationale) for adding a DID to the registry should be in the README for the registries themselves?  The JFF guide could just point there, e.g., "Follow the instructions at [DCC Community Registry](https://github.com/digitalcredentials/community-registry) to add your issuing key to the DCC Community registry."
