### ISSUE TITLE
Verifiable Request Sample

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/docs#24]
Please create a simple verifiable request - provide url & QR code.

**Comment by dmitrizagidulin** [comment]
@kayaelle - so, the way VP requests currently work with LCW is via a deep link, for example: `dccrequest://present?response_mode=post&client_id=did:key:z6MkpLDL3RoAoMRTwTgo3rs39ZwssfaPKtGdZw7AGRN7CK4W&redirect_uri=https%3A%2F%2Fclient.example.org%2Fcb&nonce=n-0S6_WzA2Mj`

Formatted, for convenience:

```
dccrequest://present?
    &response_mode=post
    &client_id=did:key:z6MkpLDL3RoAoMRTwTgo3rs39ZwssfaPKtGdZw7AGRN7CK4W              (the requester's DID)
    &redirect_uri=https%3A%2F%2Fclient.example.org%2Fcallback
    &nonce=n-0S6_WzA2Mj
```

(The notation is inspired by the OIDC4VP spec.). Where 'nonce' is the challenge, and 'redirect_uri' is the API endpoint where the wallet will POST the requested Verifiable Presentation.

So the workflow is:

1. Ensure you have LCW installed, and have at least one valid credential. For example, you can add this sample credential:
![image](https://github.com/digitalcredentials/docs/assets/947005/98366c76-7d1c-40ce-aba6-533c3ca35ef9)

2. Open the `present` deep link, above. One easy way to do it is to copy & paste it to yourself on Slack or a similar messenger, and then click on it on your mobile device. Or, you can open LCW, click the Share icon next to home, on the bottom, and click 'Scan a shared QR code', and scan:
<img width="165" alt="image" src="https://github.com/digitalcredentials/docs/assets/947005/76208d44-2a80-4e61-be41-ec5099226d23">

This kicks off the presentation request. The wallet should prompt the user to confirm sharing, select one or more credentials. When user clicks 'Submit', the wallet will wrap the selected credentials into a VP, and POST it to the URI specified in the `redirect_uri` param.

**Comment by kayaelle** [comment]
Thanks @dmitrizagidulin. This is great info.
