### ISSUE TITLE
New Test Open Badges 3.0

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/docs#27]
Please create some additional new test badges to support these issues:

- https://github.com/digitalcredentials/learner-credential-wallet/issues/460
- https://github.com/digitalcredentials/learner-credential-wallet/issues/456

Note that one of them pertains to displaying markdown in criteria.narrative. It would be helpful if one or two test credentials contained some markdown with various styling (bullets, bold, etc) and URLs.

Also, newly added to display is Achievment.AchievementType.

**Comment by kezike** [comment]
Here are several credentials that Atomic Jolt can start to use: [credentials.zip](https://github.com/digitalcredentials/docs/files/12187590/credentials.zip). Each subfolder name describes the content therein. I have tried to include as many fields as possible (e.g., `expirationDate`, `revoked`) and I have also include a number of examples of markdown. Let me know if you need more samples.

**Comment by kayaelle** [comment]
Thanks @kezike - would you please create an "example-credentials" folder at the top of: https://github.com/digitalcredentials/docs 

And add the subfolders in there?

**Comment by kezike** [comment]
@kayaelle [Here is a PR](https://github.com/digitalcredentials/docs/pull/28) that adds the credentials to the `docs` repo.

**Comment by kayaelle** [comment]
Thanks @kezike. Going to follow-up soon with issues to create a few more examples specific to upcoming pilot on degrees and for PDF printing.
