### ISSUE TITLE
Invalid tenant name in the dev doc

### ISSUE THREAD

**Issue by jaiyalas** [digitalcredentials/docs#43]
Hi, I'm trying to run testing based on the guide doc. And I noticed that, the [test cli-command](https://github.com/digitalcredentials/docs/blob/7cfee2baafdf21311a1bf650f5be7cb0ca8b18b0/deployment-guide/DCCDeploymentGuide.md?plain=1#L135) for the test of [simple signing demo](https://github.com/digitalcredentials/docs/blob/main/deployment-guide/DCCDeploymentGuide.md#simple-signing-demo), in the **deployment-guide/DCCDeploymentGuide.md** is invalid and I would get a complaint: 

```
An error occurred in the signing-service: Tenant doesn't exist.
```

I did a quick review, and i believe this is due to the fact that, in the _signing-service_, the route to _sign_ is actually fixed with `TEST_TENANT_NAME` ([src](https://github.com/digitalcredentials/signing-service/blob/3a69c4be6764a5b6322020b893055bd00c66f394/src/app.js#L26C80-L26C93)), which is fixed to `'testing'` instead of `'test'`. 

So, I think the simplest quick fix, without modifying other repos, would be using `testing` instead of `test` in that cli-command, as 
```
curl --location 'http://localhost:4005/instance/testing/credentials/issue' ...
```

**Comment by jchartrand** [comment]
Thank you for catching that @jaiyalas ! I've duly updated the doc.
